backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "images"
publish_mode: editorial_workflow

collections:
- name: "blog" # Used in routes, e.g., /admin/collections/blog
  label: "Blog" # Used in the UI
  folder: "content/posts" # The path to the folder where the documents are stored
  create: true
  fields: # The fields for each document, usually in front matter
    - {label: "Title", name: "title", widget: "string", }
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Body", name: "body", widget: "markdown"}

