backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "images"
publish_mode: editorial_workflow

collections:

- name: "pages"
  label: "Pages"
  files:  
  - file: "content/about.md"
    lable: "About"
    name: about
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}